PROC SQL; 
CREATE TABLE CENSUS.medianincome_geo 
AS 
SELECT MEDIANINCOME.GEO_ID, MEDIANINCOME.State, GEO_LOOKUP.Division, GEO_LOOKUP.Region, MEDIANINCOME.MedianIncome, MEDIANINCOME.MedianIncomeMOE 
FROM CENSUS.MEDIANINCOME MEDIANINCOME 
INNER JOIN CENSUS.GEO_LOOKUP GEO_LOOKUP 
ON 
   ( MEDIANINCOME.State = GEO_LOOKUP.State ) 
ORDER BY 4 ASC, 5 DESC; 
QUIT;

%web_open_table(CENSUS.medianincome_geo);
