--- Basic Transaction Analysis ---

--- How many unique invoices -- 541909
SELECT DISTINCT(COUNT(InvoiceNo)) as NumofUniqueInvoices
FROM `onlineretail.retail`

--- Total number of invoices by month - Pretty normal distribution as the year goes on more invoices are submitted
SELECT COUNT(InvoiceNo) as CountofInvoices, EXTRACT(MONTH FROM InvoiceDate) as InvoiceDate
FROM `onlineretail.retail`
GROUP by InvoiceDate
ORDER by InvoiceDate

--- Distribution of invoices by country - United Kingdom has the most by far
SELECT COUNT(InvoiceNo) as CountofInvoices, Country
FROM `onlineretail.retail`
GROUP by Country
ORDER by CountofInvoices DESC

--- Customer Insights - 4732
--- How many unique customers 
SELECT COUNT(DISTINCT CustomerID)
FROM `onlineretail.retail`

--- Average Number of items purchase per customers - 2.45
SELECT AVG(Quantity) / Count(CustomerID)
FROM `onlineretail.retail`


--- Average spending per customers - 1.13
SELECT AVG(UnitPrice) / Count(CustomerID)
FROM `onlineretail.retail`

--- Product Popularity
--- Top 10 most frequently purchased products?
SELECT COUNT(StockCode) as ProductCount, StockCode
FROM `onlineretail.retail`
GROUP BY StockCode
ORDER By ProductCount DESC
LIMIT 10

--- Top selling products by month
SELECT COUNT(StockCode) as ProductCount, EXTRACT(MONTH FROM InvoiceDate) as InvoiceDate
FROM `onlineretail.retail`
GROUP by InvoiceDate
ORDER by InvoiceDate

--- Top-selling products by total revenue
SELECT StockCode, SUM(UnitPrice * Quantity) as Revenue
FROM `honlineretail.retail`
GROUP BY StockCode
ORDER by Revenue DESC
LIMIT 10

--- Top-selling products for each month
WITH monthly_sales AS (
    SELECT 
        StockCode,
        Description,
        EXTRACT(YEAR FROM InvoiceDate) AS year,
        EXTRACT(MONTH FROM InvoiceDate) AS month,
        SUM(Quantity) AS total_quantity_sold
    FROM `onlineretail.retail`
    GROUP BY StockCode, Description, year, month
),
ranked_products AS (
    SELECT 
        StockCode,
        Description,
        year,
        month,
        total_quantity_sold,
        RANK() OVER (PARTITION BY year, month ORDER BY total_quantity_sold DESC) AS rank
    FROM monthly_sales
)
SELECT 
    year,
    month,
    StockCode,
    Description,
    total_quantity_sold
FROM ranked_products
WHERE rank = 1
ORDER BY year, month;


--- Revenue Trends
--- Total revenue generated by month
SELECT EXTRACT(MONTH FROM InvoiceDate) AS InvoiceMonth, SUM(UnitPrice * Quantity) AS TotalRevenue
FROM `onlineretail.retail`
GROUP BY InvoiceMonth

--- Revenue by country
SELECT Country, SUM(UnitPrice * Quantity) AS TotalRevenue
FROM `onlineretail.retail`
GROUP BY Country
ORDER by TotalRevenue DESC

--- Average revenue per invoice?
SELECT (SUM(UnitPrice * Quantity) / COUNT(DISTINCT InvoiceNo)) AS AvgRevenue
FROM `onlineretail.retail`


--- Invoice Insights
--- Average number of items per invoice
SELECT (SUM(Quantity) / COUNT(DISTINCT InvoiceNo)) AS AvgQuantity
FROM `onlineretail.retail`
